[package]
name = "deep_space"
version = "0.1.0"
authors = ["Michał Papierski <michal@papierski.net>"]
edition = "2018"

[dependencies]
num256 = "0.2"
failure = "0.1.5"
sha2 = "0.8.0"
num-bigint = "0.2.2"
num-traits = "0.2.6"
secp256k1 = "0.12.2"
ripemd160 = "0.8.0"
bech32 = "0.6.0"
serde = "1.0.91"
serde_json = "1.0.39"
serde_derive = "1.0.91"
base64 = "0.10.1"
