[package]
name = "deep_space"
version = "0.1.3"
authors = ["Michał Papierski <michal@papierski.net>", "Justin Kilpatrick <justin@althea.net>"]
repository = "https://github.com/althea-net/deep_space"
description = "A highly portable and easy to use transaction generation library for Cosmos blockchains"
license = "Apache-2.0"
edition = "2018"

[dependencies]
num256 = "0.2"
failure = "0.1"
sha2 = "0.9"
num-bigint = "0.3"
num-traits = "0.2"
secp256k1 = "0.19"
ripemd160 = "0.9"
bech32 = "0.7"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
base64 = "0.12"
clarity = {version = "0.1", optional = true}
# clarity = {path = "../clarity", optional = true}
unicode-normalization = {version = "0.1", optional = true}
pbkdf2 = {version = "0.5", optional = true}
hmac = {version = "0.9", optional = true}
rand = {version = "0.7", optional = true}

[features]
default = []
# all features, used for testing
all = ["peggy", "key_import"]
# message types and dependencies for the Peggy Cosmos Module
# only module support that requires extra deps should be featurized
peggy = ["clarity"]
# enable bip39 mnemonic + bip32 HD wallet
key_import = ["unicode-normalization", "pbkdf2", "hmac", "rand"]
